#!/bin/bash

# --                                                            # {{{1
#
# File        : dev-scripts/mgit
# Maintainer  : Felix C. Stegerman <flx@obfusk.net>
# Date        : 2012-06-26
#
# Copyright   : Copyright (C) 2012  Felix C. Stegerman
# Licence     : GPLv2
#
# --                                                            # }}}1

function die () { echo "${2:-error}: $1" >&2; exit 1; }

usage='mgit { DIR <dir> | DIRS <dir(s)> END | ENV | FIND <dir> |'
usage+=$'\n''              STDIN | SUB <dir> }'
usage+=$'\n''            <command> [ <arg(s)> ]'

# --

case "$1" in
  D|DIR)
    ds=( "$2" ) ; shift 2
  ;;

  R|DIRS)
    ds=() ; shift
    while [ "$1" != END ]; do ds+=( "$1" ); shift; done ; shift
  ;;

  E|ENV)
    ds=( $MGIT_DIRS ) ; shift
  ;;

  F|FIND)
    ds=() ; d="$2" ; shift 2
    while read -r; do ds+=( "$REPLY" ); done \
      < <( find "$d" -name '.git' | sed 's!/\.git$!!' | sort )
  ;;

  I|STDIN)
    ds=() ; shift ; while read -r; do ds+=( "$REPLY" ); done
  ;;

  S|SUB)
    ds=() ; d="$2" ; shift 2
    for x in "$d"/*; do [ -e "$x"/.git ] && ds+=( "$x" ); done
  ;;

  *)
    die "$usage" usage
  ;;
esac

# --

[ "$#" -eq 0 ] && die "$usage" usage

# --

for d in "${ds[@]}"; do
  echo "==> $d <=="
  pushd "$d" > /dev/null || die "failed to pushd $d"
    git "$@"
  popd > /dev/null
  echo
done

# vim: set tw=70 sw=2 sts=2 et fdm=marker :
